### ISSUE TITLE
ModuleNotFoundError: No module named 'mindnlp.injection'

### ISSUE THREAD

**Issue by KinhouSyou** [ultranationalism/GPT-SoVITS-mindspore#2]
请问这个问题是什么原因导致的呢？
python GPT_SOVITS/inference_webui.py
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.645 seconds.
Prefix dict has been built successfully.
Traceback (most recent call last):
File "/home/jiang/project/GPT-SoVITS-mindspore/GPT_SOVITS/inference_webui.py", line 58, in <module>
from mindnlp.injection import set_global_fp16
ModuleNotFoundError: No module named 'mindnlp.injection'

**Comment by PeterLuo2003** [comment]
是不是mindnlp大更新，用不了了

**Comment by ultism** [comment]
> 请问这个问题是什么原因导致的呢？ python GPT_SOVITS/inference_webui.py Building prefix dict from the default dictionary ... Loading model from cache /tmp/jieba.cache Loading model cost 0.645 seconds. Prefix dict has been built successfully. Traceback (most recent call last): File "/home/jiang/project/GPT-SoVITS-mindspore/GPT_SOVITS/inference_webui.py", line 58, in from mindnlp.injection import set_global_fp16 ModuleNotFoundError: No module named 'mindnlp.injection'

mindnlp在0.4后有一次大更新，换成0.3就行了
